language:
  - cpp
compiler:
  - g++
before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  # boost.
  - sudo add-apt-repository -y ppa:boost-latest/ppa

  - sudo apt-get update -qq
install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - sudo apt-get install libboost1.54-all-dev
script:
  - ./scripts/clidoc-stuff.sh build
